import requests

url = "https://api.sapling.ai/api/v1/aidetect"
payload = {"key": "sample", "text": "This is entirely generated by AI and represents a generic sentence. It proves that computers can write basic things."}
r = requests.post(url, json=payload, timeout=15)
print("Status Code:", r.status_code)
try:
    print("Response JSON:", r.json())
except Exception as e:
    print("Failed to decode JSON:", e)
    print("Response Text:", r.text)
